// Package containerfile generates a Containerfile (Dockerfile) by scanning
// a project directory.
//
//	result, err := containerfile.Generate("~/app", containerfile.Options{})
//	fmt.Println(result.Plan.Framework) // "phoenix"
//	os.WriteFile("Containerfile", []byte(result.Containerfile), 0o644)
//
// Generation has two steps that can be used separately: Scan runs the
// scanners and returns a Plan, and Render turns a Plan into text.
package containerfile

import (
	"errors"
	"fmt"
	"os"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// Scanner detects one kind of project. Scanners are tried in order and the
// first one that matches wins.
type Scanner interface {
	// Name is the identifier used by Options.Runtime.
	Name() string
	// Detect inspects src. forced is true when the user picked this scanner
	// explicitly, in which case it should produce a plan even without its
	// marker files.
	Detect(src *Source, forced bool) (*Plan, bool)
	// Render returns the Containerfile body for a plan from Detect.
	Render(plan *Plan) (string, error)
}

// Options tune Scan and Generate.
type Options struct {
	// Scanners overrides the scanner list (default: Scanners()).
	Scanners []Scanner
	// Runtime forces a scanner by name instead of auto-detecting.
	Runtime string
	// Port overrides the detected port.
	Port int
	// Env adds runtime environment variables.
	Env map[string]string
}

// Result is the output of Generate.
type Result struct {
	Plan          *Plan
	Containerfile string
	Ignore        string
}

// Errors returned by Scan.
var (
	ErrNoMatch = errors.New("could not detect the project type")
)

// UnknownRuntimeError is returned when Options.Runtime names no scanner.
type UnknownRuntimeError struct{ Name string }

func (e *UnknownRuntimeError) Error() string {
	return fmt.Sprintf("unknown runtime %q. Available: %s", e.Name, strings.Join(ScannerNames(nil), ", "))
}

// NotADirectoryError is returned when the scanned path is not a directory.
type NotADirectoryError struct{ Path string }

func (e *NotADirectoryError) Error() string { return "not a directory: " + e.Path }

// Scanners returns the built-in scanners in detection order: frameworks
// that often ship a package.json come before Node, static sites last.
func Scanners() []Scanner {
	return []Scanner{
		elixirScanner{}, rubyScanner{}, phpScanner{}, pythonScanner{}, denoScanner{},
		nodeScanner{}, goScanner{}, rustScanner{}, javaScanner{}, dotnetScanner{}, staticScanner{},
	}
}

// ScannerNames lists the names accepted by Options.Runtime.
func ScannerNames(scanners []Scanner) []string {
	if scanners == nil {
		scanners = Scanners()
	}
	names := make([]string, len(scanners))
	for i, s := range scanners {
		names[i] = s.Name()
	}
	return names
}

// Scan inspects dir and returns the plan of the first matching scanner.
func Scan(dir string, opts Options) (*Plan, error) {
	src := NewSource(dir)
	if info, err := os.Stat(src.Dir); err != nil || !info.IsDir() {
		return nil, &NotADirectoryError{src.Dir}
	}

	scanners := opts.Scanners
	if scanners == nil {
		scanners = Scanners()
	}
	forced := opts.Runtime != ""
	if forced {
		i := slices.IndexFunc(scanners, func(s Scanner) bool { return s.Name() == opts.Runtime })
		if i < 0 {
			return nil, &UnknownRuntimeError{opts.Runtime}
		}
		scanners = scanners[i : i+1]
	}

	for _, scanner := range scanners {
		if plan, ok := scanner.Detect(src, forced); ok {
			if plan.Scanner == nil {
				plan.Scanner = scanner
			}
			applyOverrides(plan, opts)
			return plan, nil
		}
	}
	return nil, ErrNoMatch
}

func applyOverrides(plan *Plan, opts Options) {
	if opts.Port != 0 {
		plan.Port = opts.Port
		if _, ok := plan.Env["PORT"]; ok {
			plan.Env["PORT"] = strconv.Itoa(opts.Port)
		}
	}
	for k, v := range opts.Env {
		plan.Env[k] = v
	}
}

// Generate scans dir and renders the Containerfile and ignore file.
func Generate(dir string, opts Options) (*Result, error) {
	plan, err := Scan(dir, opts)
	if err != nil {
		return nil, err
	}
	text, err := Render(plan)
	if err != nil {
		return nil, err
	}
	return &Result{Plan: plan, Containerfile: text, Ignore: RenderIgnore(plan)}, nil
}

// Render returns the Containerfile for a plan.
func Render(plan *Plan) (string, error) {
	body, err := plan.Scanner.Render(plan)
	if err != nil {
		return "", err
	}
	return tidy("# Generated by containerfile: " + plan.Summary() + "\n\n" + body), nil
}

var commonIgnore = []string{
	".git", ".gitignore", ".dockerignore", ".containerignore", "Dockerfile*", "Containerfile*",
	".env", ".env.*", "*.log", ".DS_Store", ".vscode", ".idea",
}

// RenderIgnore returns .dockerignore/.containerignore contents for a plan.
func RenderIgnore(plan *Plan) string {
	lines := slices.Clone(commonIgnore)
	for _, entry := range plan.Ignore {
		if !slices.Contains(lines, entry) {
			lines = append(lines, entry)
		}
	}
	return strings.Join(lines, "\n") + "\n"
}

var blankLinesRe = regexp.MustCompile(`\n{3,}`)

// tidy trims trailing whitespace, collapses blank lines and ends the text
// with exactly one newline.
func tidy(text string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	text = blankLinesRe.ReplaceAllString(strings.Join(lines, "\n"), "\n\n")
	return strings.TrimSpace(text) + "\n"
}
