package containerfile

import (
	"errors"
	"strings"
	"testing"
)

func TestScanErrors(t *testing.T) {
	if _, err := Scan(project(t, nil), Options{}); !errors.Is(err, ErrNoMatch) {
		t.Errorf("empty dir: got %v", err)
	}
	var notDir *NotADirectoryError
	if _, err := Scan("/definitely/not/here", Options{}); !errors.As(err, &notDir) {
		t.Errorf("missing dir: got %v", err)
	} else {
		assertContains(t, err.Error(), "not a directory")
	}
	var unknown *UnknownRuntimeError
	if _, err := Scan(project(t, nil), Options{Runtime: "cobol"}); !errors.As(err, &unknown) {
		t.Errorf("unknown runtime: got %v", err)
	} else {
		assertContains(t, err.Error(), `unknown runtime "cobol"`, "elixir, ruby")
	}
}

func TestForcedRuntime(t *testing.T) {
	plan, err := Scan(project(t, nil), Options{Runtime: "go"})
	if err != nil {
		t.Fatal(err)
	}
	assertEqual(t, plan.Runtime, "go")
}

func TestOverrides(t *testing.T) {
	plan, err := Scan(project(t, map[string]string{"go.mod": "module x\n\ngo 1.22\n"}),
		Options{Port: 9000, Env: map[string]string{"FOO": "bar"}})
	if err != nil {
		t.Fatal(err)
	}
	assertEqual(t, plan.Port, 9000)
	assertEqual(t, plan.Env["PORT"], "9000")
	assertEqual(t, plan.Env["FOO"], "bar")

	static, _ := Scan(project(t, map[string]string{"index.html": ""}), Options{Port: 9000})
	assertEqual(t, len(static.Env), 0)
}

type customScanner struct{}

func (customScanner) Name() string                       { return "custom" }
func (customScanner) Detect(*Source, bool) (*Plan, bool) { return newPlan("custom"), true }
func (customScanner) Render(*Plan) (string, error)       { return "FROM scratch\n", nil }

type failingScanner struct{ customScanner }

func (failingScanner) Render(*Plan) (string, error) { return "", errors.New("boom") }

func TestCustomScanner(t *testing.T) {
	result := generate(t, map[string]string{"go.mod": ""}, Options{Scanners: append([]Scanner{customScanner{}}, Scanners()...)})
	assertEqual(t, result.Plan.Runtime, "custom")
	assertContains(t, result.Containerfile, "FROM scratch")

	if _, err := Generate(project(t, nil), Options{Scanners: []Scanner{failingScanner{}}}); err == nil {
		t.Error("expected render error")
	}
}

func TestRenderTidy(t *testing.T) {
	text := generate(t, map[string]string{"index.html": "<h1>hi</h1>"}).Containerfile
	if !strings.HasPrefix(text, "# Generated by containerfile: static on port 8080\n") {
		t.Errorf("header: %q", text[:60])
	}
	refuteContains(t, text, "\n\n\n")
	if !strings.HasSuffix(text, "EXPOSE 8080\n") {
		t.Errorf("ending: %q", text[len(text)-20:])
	}
}

func TestRenderIgnore(t *testing.T) {
	ignore := generate(t, map[string]string{"Cargo.toml": "[package]\nname = \"x\"\n"}).Ignore
	assertContains(t, ignore, ".git\n", "/target\n")
}

func TestDetectionOrder(t *testing.T) {
	cases := []struct {
		files   map[string]string
		runtime string
	}{
		{map[string]string{"mix.exs": "[app: :a]", "package.json": "{}"}, "elixir"},
		{map[string]string{"Gemfile": "", "config.ru": "", "package.json": "{}"}, "ruby"},
		{map[string]string{"package.json": "{}", "index.html": ""}, "node"},
	}
	for _, c := range cases {
		assertEqual(t, generate(t, c.files).Plan.Runtime, c.runtime)
	}
}

func TestScannerNames(t *testing.T) {
	assertSlice(t, ScannerNames(nil),
		"elixir", "ruby", "php", "python", "deno", "node", "go", "rust", "java", "dotnet", "static")
}

func TestHomeExpansion(t *testing.T) {
	t.Setenv("HOME", project(t, map[string]string{"app/index.html": ""}))
	plan, err := Scan("~/app", Options{})
	if err != nil {
		t.Fatal(err)
	}
	assertEqual(t, plan.Runtime, "static")
}
